version: "2"
services:
  app:
    container_name: node-new-api
    restart: always
    build: .
    ports:
      - "4200:4300"
    links:
      - mongo
  mongo:
    container_name: mongo:latest
    image: mongo:latest
    volumes:
      - ./data:/data/db
    ports:
      - "27017:27017"